workflows:
  default:
    - name: Format Image To AVIF
      action: convert
      params:
        format: avif

    - name: Upload Image
      action: upload
      params:
        service: s3

services:
  s3:
    bucket: my-bucket
    region: us-west-1
    access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
